services:
  mysql:
    image: mysql:8.0
    container_name: techshop_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techshop_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: techshop_phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  web:
    build: .
    container_name: techshop_web
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html        # ðŸ”¥ THIS IS THE MAGIC
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: techshop_db
    depends_on:
      - mysql

volumes:
  mysql_data:
